
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7550C, LENGTH = 0xAAF4
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0xD00; /* stack */
/* No tile with memory exists to the south. */
. = 0x40000;
. += 0x10000;
/* No tile with memory exists to the west. */
. = 0x50000;
. += 0x10000;
. = 0x70D00;
memC_buff_0 = .;
. += 0x1000;
. = 0x71D00;
memC_buff_1 = .;
. += 0x1000;
. = 0x72D00;
memB_cons_buff_0 = .;
. += 0x1000;
. = 0x73D00;
memB_cons_buff_1 = .;
. += 0x1000;
. = 0x74D00;
memA_cons_buff_0 = .;
. += 0x400;
. = 0x75100;
memA_cons_buff_1 = .;
. += 0x400;
. = 0x75500;
_anonymous0 = .;
. += 0xC;
  .bss : { *(.bss*) } > data
}
INPUT(/work/vnni-int8-matmul/npu/aie/.build/32x4096x512/final.prj/matmul_i8_i32_e5b22372.o)
PROVIDE(main = core_0_2);
