
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7550C, LENGTH = 0xAAF4
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0xD00; /* stack */
. = 0x40D00;
C_L1L2_6_3_buff_0 = .;
. += 0x1000;
. = 0x41D00;
C_L1L2_6_3_buff_1 = .;
. += 0x1000;
. = 0x42D00;
B_L2L1_6_3_cons_buff_0 = .;
. += 0x1000;
. = 0x43D00;
B_L2L1_6_3_cons_buff_1 = .;
. += 0x1000;
. = 0x44D00;
A_L2L1_3_6_cons_buff_0 = .;
. += 0x400;
. = 0x45100;
A_L2L1_3_6_cons_buff_1 = .;
. += 0x400;
. = 0x45500;
_anonymous30 = .;
. += 0xC;
. = 0x50D00;
C_L1L2_3_3_buff_0 = .;
. += 0x1000;
. = 0x51D00;
C_L1L2_3_3_buff_1 = .;
. += 0x1000;
. = 0x52D00;
B_L2L1_3_3_cons_buff_0 = .;
. += 0x1000;
. = 0x53D00;
B_L2L1_3_3_cons_buff_1 = .;
. += 0x1000;
. = 0x54D00;
A_L2L1_3_3_cons_buff_0 = .;
. += 0x400;
. = 0x55100;
A_L2L1_3_3_cons_buff_1 = .;
. += 0x400;
. = 0x55500;
_anonymous27 = .;
. += 0xC;
/* No tile with memory exists to the north. */
. = 0x60000;
. += 0x10000;
. = 0x70D00;
C_L1L2_7_3_buff_0 = .;
. += 0x1000;
. = 0x71D00;
C_L1L2_7_3_buff_1 = .;
. += 0x1000;
. = 0x72D00;
B_L2L1_7_3_cons_buff_0 = .;
. += 0x1000;
. = 0x73D00;
B_L2L1_7_3_cons_buff_1 = .;
. += 0x1000;
. = 0x74D00;
A_L2L1_3_7_cons_buff_0 = .;
. += 0x400;
. = 0x75100;
A_L2L1_3_7_cons_buff_1 = .;
. += 0x400;
. = 0x75500;
_anonymous31 = .;
. += 0xC;
  .bss : { *(.bss*) } > data
}
INPUT(/work/vnni-int8-matmul/npu/aie/.build/256x4096x16384/final.prj/matmul_i8_i32_e5b22372.o)
PROVIDE(main = core_7_5);
