
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x77D0C, LENGTH = 0x82F4
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0xD00; /* stack */
. = 0x40D00;
C_L1L2_5_3_buff_0 = .;
. += 0x2000;
. = 0x42D00;
C_L1L2_5_3_buff_1 = .;
. += 0x2000;
. = 0x44D00;
B_L2L1_5_3_cons_buff_0 = .;
. += 0x1000;
. = 0x45D00;
B_L2L1_5_3_cons_buff_1 = .;
. += 0x1000;
. = 0x46D00;
A_L2L1_3_5_cons_buff_0 = .;
. += 0x800;
. = 0x47500;
A_L2L1_3_5_cons_buff_1 = .;
. += 0x800;
. = 0x47D00;
_anonymous29 = .;
. += 0xC;
. = 0x50D00;
C_L1L2_2_3_buff_0 = .;
. += 0x2000;
. = 0x52D00;
C_L1L2_2_3_buff_1 = .;
. += 0x2000;
. = 0x54D00;
B_L2L1_2_3_cons_buff_0 = .;
. += 0x1000;
. = 0x55D00;
B_L2L1_2_3_cons_buff_1 = .;
. += 0x1000;
. = 0x56D00;
A_L2L1_3_2_cons_buff_0 = .;
. += 0x800;
. = 0x57500;
A_L2L1_3_2_cons_buff_1 = .;
. += 0x800;
. = 0x57D00;
_anonymous26 = .;
. += 0xC;
. = 0x60D00;
C_L1L2_7_3_buff_0 = .;
. += 0x2000;
. = 0x62D00;
C_L1L2_7_3_buff_1 = .;
. += 0x2000;
. = 0x64D00;
B_L2L1_7_3_cons_buff_0 = .;
. += 0x1000;
. = 0x65D00;
B_L2L1_7_3_cons_buff_1 = .;
. += 0x1000;
. = 0x66D00;
A_L2L1_3_7_cons_buff_0 = .;
. += 0x800;
. = 0x67500;
A_L2L1_3_7_cons_buff_1 = .;
. += 0x800;
. = 0x67D00;
_anonymous31 = .;
. += 0xC;
. = 0x70D00;
C_L1L2_6_3_buff_0 = .;
. += 0x2000;
. = 0x72D00;
C_L1L2_6_3_buff_1 = .;
. += 0x2000;
. = 0x74D00;
B_L2L1_6_3_cons_buff_0 = .;
. += 0x1000;
. = 0x75D00;
B_L2L1_6_3_cons_buff_1 = .;
. += 0x1000;
. = 0x76D00;
A_L2L1_3_6_cons_buff_0 = .;
. += 0x800;
. = 0x77500;
A_L2L1_3_6_cons_buff_1 = .;
. += 0x800;
. = 0x77D00;
_anonymous30 = .;
. += 0xC;
  .bss : { *(.bss*) } > data
}
INPUT(/work/vnni-int8-matmul/npu/aie/.build/256x8192x4096/final.prj/matmul_i8_i32_42bea9df.o)
PROVIDE(main = core_7_4);
