
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x77D0C, LENGTH = 0x82F4
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0xD00; /* stack */
/* No tile with memory exists to the south. */
. = 0x40000;
. += 0x10000;
. = 0x50D00;
C_L1L2_4_2_buff_0 = .;
. += 0x2000;
. = 0x52D00;
C_L1L2_4_2_buff_1 = .;
. += 0x2000;
. = 0x54D00;
B_L2L1_4_2_cons_buff_0 = .;
. += 0x1000;
. = 0x55D00;
B_L2L1_4_2_cons_buff_1 = .;
. += 0x1000;
. = 0x56D00;
A_L2L1_2_4_cons_buff_0 = .;
. += 0x800;
. = 0x57500;
A_L2L1_2_4_cons_buff_1 = .;
. += 0x800;
. = 0x57D00;
_anonymous20 = .;
. += 0xC;
. = 0x60D00;
C_L1L2_1_3_buff_0 = .;
. += 0x2000;
. = 0x62D00;
C_L1L2_1_3_buff_1 = .;
. += 0x2000;
. = 0x64D00;
B_L2L1_1_3_cons_buff_0 = .;
. += 0x1000;
. = 0x65D00;
B_L2L1_1_3_cons_buff_1 = .;
. += 0x1000;
. = 0x66D00;
A_L2L1_3_1_cons_buff_0 = .;
. += 0x800;
. = 0x67500;
A_L2L1_3_1_cons_buff_1 = .;
. += 0x800;
. = 0x67D00;
_anonymous25 = .;
. += 0xC;
. = 0x70D00;
C_L1L2_0_3_buff_0 = .;
. += 0x2000;
. = 0x72D00;
C_L1L2_0_3_buff_1 = .;
. += 0x2000;
. = 0x74D00;
B_L2L1_0_3_cons_buff_0 = .;
. += 0x1000;
. = 0x75D00;
B_L2L1_0_3_cons_buff_1 = .;
. += 0x1000;
. = 0x76D00;
A_L2L1_3_0_cons_buff_0 = .;
. += 0x800;
. = 0x77500;
A_L2L1_3_0_cons_buff_1 = .;
. += 0x800;
. = 0x77D00;
_anonymous24 = .;
. += 0xC;
  .bss : { *(.bss*) } > data
}
INPUT(/work/vnni-int8-matmul/npu/aie/.build/256x4096x512/final.prj/matmul_i8_i32_42bea9df.o)
PROVIDE(main = core_6_2);
